version: '2'

services:
    postgres:
        restart: always
        build: postgis
        volumes:
            - "./.data/db:/var/lib/postgresql"
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
    php:
        build: php7-fpm
        ports:
            - 9000:9000
        links:
            - postgres:postgres
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/inowas
            - ./logs/symfony:/var/www/symfony/app/logs
        environment:
            MEMORY_LIMIT: 256
            PHP_MEM_LIMIT: 256
    nginx:
        build: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
